function prn = GoldCodeGen(prnID)

seq = comm.GoldSequence('FirstPolynomial',[9 4 0],...
              'SecondPolynomial', [9 6 4 3 0],...
              'FirstInitialConditions', [1 0 1 0 1 0 1 0 1],...
              'SecondInitialConditions', [1 0 1 0 1 0 1 0 1],...
              'Index', prnID, 'SamplesPerFrame', 511);

% seq = comm.PNSequence('Polynomial', [9 5 0],...
%                       'InitialConditions', [1 1 1 1 1 1 1 1 1],...
%                       'SamplesPerFrame', 511);         

prn = [step(seq); 0];

end

